version: '3'
services:
  appserver:
    build: .
    image: sightseeker/wildfly-deployment-demo
    ports:
      - 8080:8080
      - 9990:9990
#    deploy:
#      replicas: 2
    networks:
      - wildfly
  mysqlserver:
    image: mysql:5.6
    container_name: mysqlserver
    hostname: mysqlserver
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - wildfly
    environment:
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      MYSQL_DATABASE: demo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
networks:
  wildfly:
